### ISSUE TITLE
Incomplete sentence in Python docs?

### ISSUE THREAD

**Issue by andreaKin** [kinecosystem/kin-website-docs#10]
In 
https://github.com/kinecosystem/kin-sdk-python/blob/v2-master/README.md#channels it looks like a sentence is incomplete. 

`We highly recommend to keep only one KinAccount instance in your application, having unique channel accounts.` seems to be missing a piece.

**Comment by andreaKin** [comment]
@Ronserruya Can you help clarify the original intent of the sentence? I can't understand it myself, I'm not sure how we missed this ;)

**Comment by Ronserruya** [comment]
@andreaKin It is not incomplete, but maybe the grammar is incorrect. The intent is that you should have on KinAccount instance in your application and that this KinAccount should have multiple unique channels
