### ISSUE TITLE
Kin Explorer Testnet down

### ISSUE THREAD

**Issue by ps2-controller** [kinecosystem/kin-website-docs#26]
The [kin explorer testnet](https://testnet.kinexplorer.com/error/general/network) has been down for a few days. Not working on multiple browsers. Main net explorer seems fine. Here's a screenshot of the issue. 
No error reporting in the console; unable to troubleshoot this. 

<img width="1170" alt="Screen Shot 2019-05-06 at 5 15 16 PM" src="https://user-images.githubusercontent.com/37810163/57257151-9ad18000-7026-11e9-8d39-f5b60b215297.png">

**Comment by cnotethegr8** [comment]
Hey, the kin explorer is not made by 

https://github.com/chancity/kinexplorer
