### ISSUE TITLE
Deadlock in python docs

### ISSUE THREAD

**Issue by TheBubblePopped** [kinecosystem/kin-website-docs#56]
First of all, this problem occurs only on chromium. Chrome and Firefox are fine. 

Imagine i am browsing @  https://docs.kin.org/intro

If i now choose python from the left bar and click python api reference  it redirects me to
https://docs.kin.org/api-ref/python-sdk/ as expected, but.... BUT 

it creates a deadlock. I can't go back to the previous page i would have to open a new tab and navigate there again from scratch. It just reloads the same page when i try to go back.
It should go back.

Btw, nice work. I really like the changes.

**Comment by Ronserruya** [comment]
Thanks for the report, I guess it happens because of the redirection method used, we will check it out

**Comment by cnotethegr8** [comment]
This is a [Docusaurus](https://github.com/facebook/docusaurus) bug.
